export const FETCH_CURRENT_DIRECTORIES = "FETCH_CURRENT_DIRECTORIES";
export const FETCH_CURRENT_CARDS = "FETCH_CURRENT_CARDS";
export const CHANGE_CURRENT_DIR = "CHANGE_CURRENT_DIR";
export const PUSH_DIR = "PUSH_DIR";
export const POP_DIR = "POP_DIR";
export const ADD_CARD = "PUSH_CARD";
export const PUSH_DIR_IN_DIRS = "PUSH_DIR_IN_DIRS";
export const UPDATE_CARD = "UPDATE_CARD";
